### ISSUE TITLE
The Font Viewer Tool Should Display Bookmarked Items in a Collection

### ISSUE THREAD

**Issue by joekotvas** [chingu-voyages/v47-tier2-team-17#120]
**__Task Description__**
* When a font style is bookmarked, it should be pushed to an object in local storage. 
* The contents of this object should be displayed in a "Your Collection" section, as seen in the Figma mockup (pictured below.)
* An action button to select a given bookmarked font style should appear on hover
* Functionality to remove saved font styles should be integrated into the Your Collection section, as seen in the Color Picker tool.

This should all look very much like what is seen in the Color Picker tool.

<img width="1106" alt="Screenshot 2024-02-19 at 11 11 45 PM" src="https://github.com/chingu-voyages/v47-tier2-team-17/assets/8323435/535db9fd-3e8b-45bf-aecf-fd8cb1654f2a">

**Comment by Stevensauro** [comment]
Done during Joe's bookmark rework
