### ISSUE TITLE
Search field should not be auto-focused on mobile.

### ISSUE THREAD

**Issue by david-nyc-pm** [chingu-voyages/v47-tier2-team-17#124]
**Description:** On both desktop and mobile web, the curser automatically appears in the search bar upon entering the page. The actionable state is automatically enabled, which is noticeable as the outline of the box is currently "purple" by default when visiting the page. By having the curser default to the search bar, we are making assumptions that the first thing a user wants to do is use the search function. However, there are other ways a user can locate character info such as by tapping on the one of many tabs and/or scrolling through the list(s) of characters.

**Expected result:** Upon tapping the corresponding tab, user should be taken the Character Finder screen without the cursor immediately appearing in the search bar. 

![Screen Shot 2024-02-20 at 12 35 59 PM](https://github.com/chingu-voyages/v47-tier2-team-17/assets/7538157/af7422ef-3ebc-4682-bc67-c2f3489adc11)

**Comment by ghost** [comment]
Hi @david-nyc-pm, focusing the search bar on page load was a requested in response to a PR I submitted - PR #49. Has this requirement changed? @joekotvas could you provide more insight on whether this needs to be changed again?

**Comment by joekotvas** [comment]
Hi @imadrig! I've conferred with @david-nyc-pm and the issue is that on mobile the keyboard pops up and covers half the screen when the tool loads. On desktop this is not an issue.

The solution we came up with is to only autofocus the search field on desktop.

**Comment by ghost** [comment]
Understood, thanks for clarifying!
