### ISSUE TITLE
"Emoji" icon needs to be updated on mobile web

### ISSUE THREAD

**Issue by david-nyc-pm** [chingu-voyages/v47-tier2-team-17#125]
**Describe the problem:** The icon for the "emoji" tab needs to be updated to match the design on mobile web.

**Desktop:**
![Screen Shot 2024-02-20 at 12 54 33 PM](https://github.com/chingu-voyages/v47-tier2-team-17/assets/7538157/3b168af6-ad0e-4d9e-a397-fdd4454c8f1a)

**Mobile web:**
![characterfinder](https://github.com/chingu-voyages/v47-tier2-team-17/assets/7538157/20848c67-b73c-4aae-b3f6-aaa6575488ed)

**Comment by joekotvas** [comment]
This will require updating the character finder tabs to use the <Icon component, allowing us to pass in Material Symbol icon names. The Material Symbol name slug for the smiley face here is "mood." We'll take advantage of the new functionality to also change the star to the more rounded MDS "star."
