### ISSUE TITLE
Field Labels Overlap Values for Opacity

### ISSUE THREAD

**Issue by joekotvas** [chingu-voyages/v47-tier2-team-17#86]
**Describe the problem**
The field label text overlaps the field value for the alpha field.

**Expected behavior**
The values should be more to the right, so that there is no overlap with the field labels.

**To Reproduce**
Load https://development-fetools.netlify.app/colors?color=a1a95d on mobile and scroll to the Color Codes section.

**Screenshots**
![IMG_7025](https://github.com/chingu-voyages/v47-tier2-team-17/assets/8323435/7a0fb42e-73eb-4f08-bea9-173f1580c1e7)

**Your Environment:**
 - iPhone 12 Pro
 - Chrome Mobile

**Comment by Stevensauro** [comment]
Fixed overlap
