### ISSUE TITLE
The Character Finder search field button needs to be replaced with a simple icon overlay. 

### ISSUE THREAD

**Issue by joekotvas** [chingu-voyages/v47-tier2-team-17#89]
**Describe the problem**
The search button on the character finder page is vestigial; it no longer has any function. All search functionality is executed on change on the search text input field. This creates an awkward look when tabbing across the page, as the field is selected separately from the button.

**Expected behavior**
When tabbing across the search field, the entire search area including the icon should be enclosed by the focus ring. The search icon should not be independently focusable. Also, the focus ring should be purple.

**Screenshots**
<img width="691" alt="Screenshot 2024-02-16 at 11 15 58 PM" src="https://github.com/chingu-voyages/v47-tier2-team-17/assets/8323435/00684ceb-193b-488b-aa86-6b32a6807e92">
<img width="691" alt="Screenshot 2024-02-16 at 11 16 02 PM" src="https://github.com/chingu-voyages/v47-tier2-team-17/assets/8323435/da122aa7-271c-4a32-b27a-1c1ba52ba6f7">

**Comment by ghost** [comment]
This is resolved - pull request #106.
