### ISSUE TITLE
Code Block Background Color should be Lighter

### ISSUE THREAD

**Issue by joekotvas** [chingu-voyages/v47-tier2-team-17#90]
We can use tailwind color bg-neutral-100 or hex #f5f5f5.

**Current Color**
<img width="1110" alt="Screenshot 2024-02-16 at 11 24 43 PM" src="https://github.com/chingu-voyages/v47-tier2-team-17/assets/8323435/02c7de60-c2e2-44c0-be87-ad8744177eaa">

**Expected Color**
<img width="853" alt="Screenshot 2024-02-16 at 11 30 51 PM" src="https://github.com/chingu-voyages/v47-tier2-team-17/assets/8323435/b5439d35-54f7-48cd-817a-653d26722159">

**Comment by amansinghgill** [comment]
Will be updated in my next PR
