### ISSUE TITLE
Color Picker does not update the selected color on forward/back navigation

### ISSUE THREAD

**Issue by joekotvas** [chingu-voyages/v47-tier2-team-17#92]
**Describe the problem**
The forward/back buttons change the url query color parameter but do not update the color in the picker area.

**Actual behavior**
When selecting a given color with the picker, then selecting a different color, the url query string changes as expected. However, when the back button is pressed, although the color query parameter changes, the color in the browser window stays the same.

**Expected behavior**
The color in the picker and color code section should always match the color reflected in the url color query parameter.

**To Reproduce**
1. Go to https://development-fetools.netlify.app/colors?color=663399
2. Click on the color picker canvas or sliders to pick any other color.
3. Press the browser back button.
4. Note that while the color query parameter changes, the color reflected in the picker tool is not updated to match.

**Screenshots**
<img width="601" alt="Screenshot 2024-02-16 at 11 44 17 PM" src="https://github.com/chingu-voyages/v47-tier2-team-17/assets/8323435/5a3226b7-b2c2-494d-9f3e-97c91604421c">

**Environment:**
 - Chrome, latest.

**Comment by Stevensauro** [comment]
Issues fixed on this branch
